site_name: ShrinkAI
site_description: ShrinkAI Documentation

theme:

  name: material
  logo: assets/shrinkai-logo-no-background-title.png
  favicon: assets/shrinkai-logo-nobackground.png

  features:
    - navigation.tabs
    - navigation.indexes
    #- navigation.instant
    #- navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    #- search.share
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  
  palette:
    - scheme: shrinkai
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: shrinkai-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light Mode

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      lang: en
      suggest: true
      highlight: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            show_signature_annotations: true 
            separate_signature: true
            docstring_section_style: table
            show_symbol_type_heading: true 
            show_category_heading: true
            summary: true
  - mkdocs-jupyter:
      no_prompt: true
      enable_math: true
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - toc:
      toc_depth: 4

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quickstart: a_quick_start.ipynb
  - Tutorials:
    - Distillation of Vision models on CIFAR10: tutorials/01_distillation_vision_cifar10.ipynb
    - Distillation of Transformers on SST-2: tutorials/02_distillation_nlp_sst2.ipynb
    - Distillation of Language Models for text generation: tutorials/03_distillation_llm_generation.ipynb
  - API Reference:
    - Distillation:
      - shrinkai.distillation: api/distillation.md
      - shrinkai.distillation.losses: api/loss.md
    - Compression: 
      - shrinkai.compression.pruning: api/pruning.md
      - shrinkai.compression.quantization: api/quantization.md
    - Other:
      - shrinkai.analysis: api/analysis.md
      - shrinkai.adapters: api/adapters.md
      - shrinkai.profiler: api/profiler.md